package mocks

import gateways "github.com/ghmeier/coinage/gateways"
import mock "github.com/stretchr/testify/mock"
import models "github.com/jakelong95/TownCenter/models"
import stripe "github.com/stripe/stripe-go"
import warehousemodels "github.com/lcollin/warehouse/models"

// Stripe is an autogenerated mock type for the Stripe type
type Stripe struct {
	mock.Mock
}

// AddSource provides a mock function with given fields: id, token
func (_m *Stripe) AddSource(id string, token string) (*stripe.Customer, error) {
	ret := _m.Called(id, token)

	var r0 *stripe.Customer
	if rf, ok := ret.Get(0).(func(string, string) *stripe.Customer); ok {
		r0 = rf(id, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCustomer provides a mock function with given fields: id
func (_m *Stripe) DeleteCustomer(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccount provides a mock function with given fields: id
func (_m *Stripe) GetAccount(id string) (*stripe.Account, error) {
	ret := _m.Called(id)

	var r0 *stripe.Account
	if rf, ok := ret.Get(0).(func(string) *stripe.Account); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomer provides a mock function with given fields: id
func (_m *Stripe) GetCustomer(id string) (*stripe.Customer, error) {
	ret := _m.Called(id)

	var r0 *stripe.Customer
	if rf, ok := ret.Get(0).(func(string) *stripe.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlan provides a mock function with given fields: id, pid
func (_m *Stripe) GetPlan(id string, pid string) (*stripe.Plan, error) {
	ret := _m.Called(id, pid)

	var r0 *stripe.Plan
	if rf, ok := ret.Get(0).(func(string, string) *stripe.Plan); ok {
		r0 = rf(id, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccount provides a mock function with given fields: country, user, roaster
func (_m *Stripe) NewAccount(country string, user *models.User, roaster *models.Roaster) (*stripe.Account, error) {
	ret := _m.Called(country, user, roaster)

	var r0 *stripe.Account
	if rf, ok := ret.Get(0).(func(string, *models.User, *models.Roaster) *stripe.Account); ok {
		r0 = rf(country, user, roaster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *models.User, *models.Roaster) error); ok {
		r1 = rf(country, user, roaster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomer provides a mock function with given fields: token, userID
func (_m *Stripe) NewCustomer(token string, userID string) (string, error) {
	ret := _m.Called(token, userID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(token, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(token, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlan provides a mock function with given fields: id, item, freq
func (_m *Stripe) NewPlan(id string, item *warehousemodels.Item, freq string) (*stripe.Plan, error) {
	ret := _m.Called(id, item, freq)

	var r0 *stripe.Plan
	if rf, ok := ret.Get(0).(func(string, *warehousemodels.Item, string) *stripe.Plan); ok {
		r0 = rf(id, item, freq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *warehousemodels.Item, string) error); ok {
		r1 = rf(id, item, freq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: id, planID
func (_m *Stripe) Subscribe(id string, planID string) (*stripe.Sub, error) {
	ret := _m.Called(id, planID)

	var r0 *stripe.Sub
	if rf, ok := ret.Get(0).(func(string, string) *stripe.Sub); ok {
		r0 = rf(id, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Sub)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ gateways.Stripe = (*Stripe)(nil)
